"use client";

import type { ApprovalDetail } from "@docs-agent/control-plane";
import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { Button } from "@/components/ui/button";

export function ApprovalDecisionActions({ approval }: { approval: ApprovalDetail }) {
  const router = useRouter(); const [reason, setReason] = useState(""); const [error, setError] = useState<string>(); const [message, setMessage] = useState<string>(); const [pending, startTransition] = useTransition();
  if (approval.displayState !== "pending") return <p className="text-sm leading-6 text-muted-foreground">This request is {approval.displayState.replaceAll("-", " ")}. Eve will not receive another response from this inbox record.</p>;
  function submit(decision: "approve" | "deny") { setError(undefined); setMessage(undefined); if (!reason.trim()) { setError("Add a reason before deciding."); return; } startTransition(async () => { try { const response = await fetch(`/api/operator/approvals/${encodeURIComponent(approval.id)}/decision`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ decision, reason, idempotencyKey: crypto.randomUUID() }) }); const body = await response.json() as { error?: string; approval?: ApprovalDetail }; if (!response.ok || !body.approval) { setError(body.error ?? "The approval decision was rejected."); return; } setMessage(`Decision submitted once: ${decision}. Refreshing Eve state…`); setReason(""); router.refresh(); } catch { setError("The decision could not reach the server."); } }); }
  return <div className="grid gap-4" data-approval-actions><label className="grid gap-2 text-sm font-medium">Reason for this decision<textarea className="min-h-28 rounded-md border border-input bg-background px-3 py-2 text-sm leading-6 outline-none focus:border-ring focus:ring-3 focus:ring-ring/30" maxLength={2_000} onChange={(event) => setReason(event.target.value)} placeholder="What did you review, or what must change?" value={reason} /></label><div className="flex flex-wrap gap-2"><Button disabled={pending} onClick={() => submit("approve")} type="button">{pending ? "Submitting…" : "Approve and resume"}</Button><Button disabled={pending} onClick={() => submit("deny")} type="button" variant="destructive">Deny request</Button></div>{message ? <p className="text-sm text-[#45613f]" role="status">{message}</p> : null}{error ? <p className="text-sm text-destructive" role="alert">{error}</p> : null}<p className="text-xs leading-5 text-muted-foreground">The server re-reads Eve, supplies your authenticated operator identity, and resumes the original request once. The browser cannot choose the audit actor.</p></div>;
}
