import assert from "node:assert/strict"; import { spawn, type ChildProcessWithoutNullStreams } from "node:child_process"; import { mkdtemp, rm } from "node:fs/promises"; import { createServer } from "node:net"; import { tmpdir } from "node:os"; import { dirname, join } from "node:path"; import { fileURLToPath } from "node:url"; import { Client, type InputRequest } from "eve/client"; import { ApprovalInboxError, decideApproval, recordApprovalBatch } from "../../../packages/control-plane/src/approval-inbox"; import { migrateDocsAgentDatabase } from "../../../packages/control-plane/src/db/client";
const appRoot = dirname(dirname(fileURLToPath(import.meta.url))); const fixtureRoot = join(appRoot, "fixtures", "approval-agent"); const eveBin = join(appRoot, "node_modules", "eve", "bin", "eve.js"); const root = await mkdtemp(join(tmpdir(), "docs-agent-approval-integration-")); const originalDatabaseUrl = process.env.DOCS_AGENT_DATABASE_URL; const originalEveUrl = process.env.DOCS_AGENT_EVE_URL; const originalVercel = process.env.VERCEL; const originalNodeEnv = process.env.NODE_ENV; const port = await availablePort(); const host = `http://127.0.0.1:${port}`; let child: ChildProcessWithoutNullStreams | undefined; let logs = "";
try { process.env.DOCS_AGENT_DATABASE_URL = `file:${join(root, "approval.sqlite")}`; process.env.DOCS_AGENT_EVE_URL = host; delete process.env.VERCEL; delete process.env.NODE_ENV; await migrateDocsAgentDatabase(); child = spawn(process.execPath, [eveBin, "dev", "--no-ui", "--host", "127.0.0.1", "--port", String(port), "--logs", "none"], { cwd: fixtureRoot, env: { ...process.env, NODE_ENV: "development" }, stdio: "pipe" }); child.stdout.on("data", (chunk) => { logs += String(chunk); }); child.stderr.on("data", (chunk) => { logs += String(chunk); }); await waitForAgent(host, child);
  const client = new Client({ host }); const first = client.session(); const firstResult = await (await first.send("Publish the checked fixture.")).result(); const firstRequest = requireApproval(firstResult.events); assert.equal(firstResult.status, "waiting"); await record(firstRequest, firstResult.sessionId, first.state.continuationToken!, "integration-approve"); const approved = await decideApproval({ id: firstRequest.requestId, decision: "approve", reason: "Fixture evidence reviewed.", idempotencyKey: "integration-approve-once", actor: { id: "operator-1", login: "operator" } }); assert.equal(approved.approval.status, "approved"); const approvedEvents = await collectExisting(first); assert.match(JSON.stringify(approvedEvents), /"published":true/); await assert.rejects(() => decideApproval({ id: firstRequest.requestId, decision: "approve", reason: "Duplicate.", idempotencyKey: "integration-approve-twice", actor: { id: "operator-1", login: "operator" } }), (error) => error instanceof ApprovalInboxError && error.code === "already-answered");
  const second = client.session(); const secondResult = await (await second.send("Publish another fixture.")).result(); const secondRequest = requireApproval(secondResult.events); await record(secondRequest, secondResult.sessionId, second.state.continuationToken!, "integration-deny"); const denied = await decideApproval({ id: secondRequest.requestId, decision: "deny", reason: "Fixture denial.", idempotencyKey: "integration-deny-once", actor: { id: "operator-1", login: "operator" } }); assert.equal(denied.approval.status, "denied"); const deniedEvents = await collectExisting(second); assert.doesNotMatch(JSON.stringify(deniedEvents), /"published":true/);
  const native = client.session(); const nativeResult = await (await native.send("Publish through the channel-native flow.")).result(); const nativeRequest = requireApproval(nativeResult.events); const resumed = await native.send({ inputResponses: [{ requestId: nativeRequest.requestId, optionId: "approve" }] }); const nativeCompleted = await resumed.result(); assert.match(JSON.stringify(nativeCompleted.events), /"published":true/);
} catch (error) { if (logs.trim()) console.error(logs); throw error; } finally { child?.kill("SIGTERM"); restore("DOCS_AGENT_DATABASE_URL", originalDatabaseUrl); restore("DOCS_AGENT_EVE_URL", originalEveUrl); restore("VERCEL", originalVercel); restore("NODE_ENV", originalNodeEnv); await rm(root, { recursive: true, force: true }); }
console.log("Real Eve approval inbox integration checks passed.");
async function record(request: InputRequest, sessionId: string, token: string, key: string) { await recordApprovalBatch({ sessionId, runId: "turn_0", continuationToken: token, trigger: "terminal", requester: "fixture-user", destination: "https://github.com/example/docs", requests: [request], requestedAt: new Date().toISOString() }); assert.equal(key.length > 0, true); }
function requireApproval(events: readonly unknown[]) { for (const event of events) { const row = asRecord(event); const data = asRecord(row.data); if (row.type === "input.requested" && Array.isArray(data.requests)) { const request = data.requests.find((value) => asRecord(value).display === "confirmation"); if (request) return request as InputRequest; } } throw new Error("Fixture did not emit an approval request."); }
async function collectExisting(session: ReturnType<Client["session"]>) { const events: unknown[] = []; const deadline = Date.now() + 10_000; for await (const event of session.stream()) { events.push(event); if (event.type === "session.waiting" || event.type === "session.completed" || Date.now() > deadline) break; } return events; }
async function availablePort() { return new Promise<number>((resolve, reject) => { const server = createServer(); server.once("error", reject); server.listen(0, "127.0.0.1", () => { const address = server.address(); if (typeof address !== "object" || !address) return reject(new Error("No port.")); server.close((error) => error ? reject(error) : resolve(address.port)); }); }); }
async function waitForAgent(host: string, process: ChildProcessWithoutNullStreams) { const deadline = Date.now() + 30_000; while (Date.now() < deadline) { if (process.exitCode !== null) throw new Error(`Eve fixture exited with ${process.exitCode}.`); try { if ((await fetch(`${host}/eve/v1/health`)).ok) return; } catch {} await new Promise((resolve) => setTimeout(resolve, 200)); } throw new Error("Timed out waiting for Eve."); }
function asRecord(value: unknown): Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value) ? value as Record<string, unknown> : {}; } function restore(name: string, value: string | undefined) { if (value === undefined) delete process.env[name]; else process.env[name] = value; }
